### ISSUE TITLE
missing membership form pdf

### ISSUE THREAD

**Issue by tesu** [mit-anime/mit-anime.github.io#11]
https://mit-anime.github.io/library/anime_membershipform.pdf 404s

**Comment by tesu** [comment]
(it is linked on this page https://mit-anime.github.io/library/rules)

**Comment by ed1d1a8d** [comment]
Fixed via https://github.com/mit-anime/mit-anime.github.io/commit/1cfbe952e64a0d134648cd087b6f59dfa323cb13.
