### ISSUE TITLE
Indication of calendar if 3rd party iframes are disabled

### ISSUE THREAD

**Issue by mjsir911** [mit-anime/mit-anime.github.io#3]
On my machine the calendar on the front page doesn't show up unless I explicitly allow it to, but there was no indication something was supposed to go on the blank space.

![anime](https://user-images.githubusercontent.com/17185986/69501317-d2741c80-0ed1-11ea-8362-edef772f0471.png)

@ed1d1a8d suggested having alt text on the iframe

**Comment by ed1d1a8d** [comment]
Fixed via https://github.com/mit-anime/mit-anime.github.io/commit/3f02daa23d1823b706cb68136f77ecb8c42f4235. Good stuff @mjsir911!
