### ISSUE TITLE
Base tag wrong

### ISSUE THREAD

**Issue by tesu** [mit-anime/mit-anime.github.io#6]
Issue caused by the migration, [mit-anime.github.io](mit-anime.github.io) has broken links + broken css because base is set to `pages/mit-anime/website/`

**Comment by mjsir911** [comment]
So on the developer box you access the website through `localhost:400/{site.baseurl}`. 

Does github pages not support [`site.baseurl`](https://github.com/mit-anime/mit-anime.github.io/blob/a246a0c322972db4d39024158cdb3c350b63830c/_config.yml#L25)?

**Comment by ed1d1a8d** [comment]
Fixed via https://github.com/mit-anime/mit-anime.github.io/commit/3d23db891043ff2bb02039ef6c3a178c76703a8d.
